sudo: false
dist: trusty
language: node_js
node_js:
  - "8"
git:
  submodules: false
cache:
  yarn: true

install:
  - git submodule init
  - yarn submodule
  - yarn
jobs:
  include:
    - stage: build packages
      script:
        - (cd packages/react-icons/ && yarn build && npm pack)
        - (cd packages/preview/ && yarn build)
        - (cd packages/demo/ && yarn test && yarn build)
        - |
          if [ -n "$NETLIFY_ACCESS_TOKEN" ]; then
            NETLIFY_AUTH_TOKEN=$NETLIFY_ACCESS_TOKEN yarn netlify deploy;
          fi
