sudo: false
dist: trusty
language: node_js
node_js:
  - "8"
cache:
  yarn: true
install:
  - yarn
  - yarn submodule
jobs:
  include:
    - stage: build packages
      script:
        - (cd packages/react-icons/ && yarn build)
    - stage: build preview site
      script:
        - (cd packages/preview/ && yarn build)
    - stage: deploy preview site
      script:
        - yarn netlify deploy --draft --access-token $NETLIFY_ACCESS_TOKEN
